[package]
name = "olecfsdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description.workspace = true

[dependencies]
cfb = { workspace = true }
olecfsdk-derive = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
web-time = { workspace = true }

